version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ziohelp-postgres
    environment:
      POSTGRES_DB: ziohelpdb
      POSTGRES_USER: ziohelpuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ziohelp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: 